# .github/workflows/ci.yml
name: Python CI/CD Pipeline

# Trigger on pushes to any branch and on pull requests targeting main
on:
  push:
    branches:
      - '**'        # run on all branches (optionally, you can restrict to feature/* or main)
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repository
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 2) Set up Python (choose whichever version you prefer)
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3) Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4) Run pytest
      - name: Run Pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q
